### PR TITLE
Changing extension to make use of dependency injection instead of hard-coding

### PR DESCRIPTION
**Pull request by AdmiringWorm**
Now first of, this is just provided as an example of what I've found out to work, and could definitely be improved quite alot.

This example is being provided as I believe it could be useful, especially in cases when/if unit testing is to be implemented.

If you have any questions about the changes, please let me know. I did try to explain a little in the commit message (hence the many different commits)

/cc @gep13 

EDIT: As this is an example, I didn't bother to create an issue.

### CODE REVIEW

**Comment by gep13** [comment]
This looks very cool!  I haven't played at all with dependency injection in TS yet, but I am definitely going to dig into this some more!

**Comment by gep13** [comment]
Absolutely.  I have made use of it extensively in .Net applications, but hadn't checked to see what existed in TS/JavaScript.  This looks like it has everything that is needed though.  Thanks again for creating this PR!

**Comment by AdmiringWorm** [comment]
Indeed, I believe it have more or less everything needed.
I know there are other DI frameworks for TS though, but inversify was the only one I found a blog post on how to implement it (which is pretty much were most of the code here comes from)

Blog Post: https://rpeshkov.net/blog/vscode-extension-di/

**Comment by AdmiringWorm** [comment]
Oh I see, I've missed something. I've forgotten to import 'reflect-metadata' which is actually required (don't know why, and can't understand why it worked without it).
Let me change that

**Comment by gep13** [comment]
@AdmiringWorm thank you for the link to that blog post!

**Comment by gep13** [comment]
Relates to #5

**Comment by gep13** [comment]
@AdmiringWorm your changes have been merged, thanks for your contribution 👍

**Pull request merged**
